services:
  db:
    image: postgres:15-alpine 
    container_name: postgres_dw
    restart: always
    environment:
      POSTGRES_DB: bike_db
      POSTGRES_USER: bike_user
      POSTGRES_PASSWORD: 1660902345
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: